"""
Django settings for commerce project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables du fichier .env (sans dépendance python-dotenv)
_env_path = BASE_DIR / ".env"
if _env_path.exists():
    with open(_env_path, encoding="utf-8") as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _key, _, _val = _line.partition("=")
                _key, _val = _key.strip(), _val.strip().strip('"').strip("'")
                if _key:
                    os.environ.setdefault(_key, _val)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8&&2*v55a%7rozim(6sltcd@huc0!$yi&9n^y%_7)!z0!1rrez'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'corsheaders',  # ajouté
    'rest_framework',           # <-- ajoute DRF
    'rest_framework.authtoken', # <-- optionnel : si tu veux TokenAuth
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'commerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'api.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'commerce.wsgi.application'



# Configuration minimale pour Django REST framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",  # si utilisé
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    # Rate limiting pour protéger contre le scraping
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",  # 100 requêtes par heure pour les utilisateurs anonymes
        "user": "1000/hour",  # 1000 requêtes par heure pour les utilisateurs authentifiés
    },
}
# ...existing code...



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "192.168.8.101",  # IP du PC pour accès réseau
]

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:9100",       # Next.js PC
    "http://127.0.0.1:9100",       # Next.js PC
    "http://192.168.8.101:9100",   # Next.js téléphone
]

CORS_ALLOW_CREDENTIALS = True  # pour les cookies/session

# CSRF
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:9100",
    "http://127.0.0.1:9100",
    "http://192.168.8.101:9100",  # Frontend mobile
    "http://192.168.8.101:9000",  # Django
]

# Cookies pour dev
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# Configuration des cookies pour l'admin (même domaine)
# Pour l'admin Django, on garde les valeurs par défaut
SESSION_COOKIE_SAMESITE = "Lax"  # Changé de "None" à "Lax"
CSRF_COOKIE_SAMESITE = "Lax"  # Changé de "None" à "Lax"
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False





# ... existing code ...

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Images uploadées par les utilisateurs)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# PayPal (paiement géré côté backend uniquement)
# Définir dans l'environnement : PAYPAL_CLIENT_ID, PAYPAL_CLIENT_SECRET
# Optionnel : PAYPAL_MODE=sandbox|live, PAYPAL_CURRENCY=EUR, PAYPAL_CFA_TO_EUR=655.957


