# Generated by Django 5.2.7 on 2026-01-09 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('statut_juridique', models.CharField(blank=True, max_length=255, null=True, verbose_name='Statut juridique')),
                ('rc_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro RC')),
                ('nif', models.CharField(blank=True, max_length=255, null=True, verbose_name='NIF')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('support_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone support')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email support')),
                ('facebook_page', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name="Horaires d'ouverture")),
                ('about', models.TextField(blank=True, null=True, verbose_name='À propos')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mots-clés SEO')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png'])])),
                ('cgv', models.FileField(blank=True, null=True, upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('privacy_policy', models.TextField(blank=True, null=True, verbose_name='Politique de confidentialité')),
                ('refund_policy', models.TextField(blank=True, null=True, verbose_name='Politique de remboursement')),
                ('shipping_policy', models.TextField(blank=True, null=True, verbose_name='Politique de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
