# Generated by Django 5.2.8 on 2026-01-14 00:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_products_category_limit', models.PositiveIntegerField(default=3, help_text='Nombre de catégories à afficher dans la section Nouveaux produits')),
                ('new_products_per_category_limit', models.PositiveIntegerField(default=12, help_text='Nombre de produits récents à afficher par catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres de page',
                'verbose_name_plural': 'Paramètres de page',
            },
        ),
        migrations.CreateModel(
            name='ProductFlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('statut_juridique', models.CharField(blank=True, max_length=255, null=True, verbose_name='Statut juridique')),
                ('rc_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro RC')),
                ('nif', models.CharField(blank=True, max_length=255, null=True, verbose_name='NIF')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('support_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone support')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email support')),
                ('facebook_page', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name="Horaires d'ouverture")),
                ('about', models.TextField(blank=True, null=True, verbose_name='À propos')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mots-clés SEO')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png'])])),
                ('cgv', models.FileField(blank=True, null=True, upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('privacy_policy', models.TextField(blank=True, null=True, verbose_name='Politique de confidentialité')),
                ('refund_policy', models.TextField(blank=True, null=True, verbose_name='Politique de remboursement')),
                ('shipping_policy', models.TextField(blank=True, null=True, verbose_name='Politique de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('shot_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text="URL externe de l'image source", max_length=500, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_2', models.CharField(blank=True, help_text='Deuxième commentaire marketing', max_length=255)),
                ('comment_1', models.CharField(blank=True, help_text='Premier commentaire marketing', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Afficher ce produit dans le carousel')),
                ('position', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le carousel")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='api.product')),
            ],
            options={
                'verbose_name': 'Carousel Product',
                'verbose_name_plural': 'Carousel Products',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FlashProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('flash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.productflash')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_price', models.DecimalField(decimal_places=2, help_text='Prix promotionnel', max_digits=10)),
                ('label', models.CharField(blank=True, help_text='Ex: Promo, -20%, Black Friday', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Promotion active ou non')),
                ('is_featured', models.BooleanField(default=False, help_text='Mettre cette promotion en avant (homepage / hero)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Date de début de la promotion', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Date de fin de la promotion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='api.product')),
            ],
            options={
                'verbose_name': 'Promotion product',
                'verbose_name_plural': 'Promotions products',
            },
        ),
    ]
