# Generated by Django 5.2.8 on 2026-01-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flashproductitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('flash',), name='unique_main_product_per_flash'),
        ),
    ]
