# Generated by Django 5.2.7 on 2026-01-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sitesettings_options_category_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL externe de l'image source", max_length=500, null=True),
        ),
    ]
