# Generated by Django 5.2.8 on 2026-01-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flashproductitem_unique_main_product_per_flash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashproductitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='productflash',
            name='secondary_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productflash',
            name='secondary_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
