# Generated by Django 5.2.8 on 2026-01-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_flashproductitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productflash',
            name='secondary_products',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez plusieurs produits secondaires pour ce flash', related_name='flash_secondary', to='api.product'),
        ),
    ]
