# Generated by Django 5.2.7 on 2026-01-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sitesettings_options_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_2', models.CharField(blank=True, help_text='Deuxième commentaire marketing', max_length=255)),
                ('comment_1', models.CharField(blank=True, help_text='Premier commentaire marketing', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Afficher ce produit dans le carousel')),
                ('position', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le carousel")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='api.product')),
            ],
            options={
                'verbose_name': 'Produit du carousel',
                'verbose_name_plural': 'Produits du carousel',
                'ordering': ['position'],
            },
        ),
    ]
