# Generated by Django 5.2.7 on 2026-01-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productcarousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcarousel',
            options={'ordering': ['position'], 'verbose_name': 'Carousel Product', 'verbose_name_plural': 'Carousel Products'},
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_price', models.DecimalField(decimal_places=2, help_text='Prix promotionnel', max_digits=10)),
                ('label', models.CharField(blank=True, help_text='Ex: Promo, -20%, Black Friday', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Promotion active ou non')),
                ('is_featured', models.BooleanField(default=False, help_text='Mettre cette promotion en avant (homepage / hero)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Date de début de la promotion', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Date de fin de la promotion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='api.product')),
            ],
            options={
                'verbose_name': 'Promotion produit',
                'verbose_name_plural': 'Promotions produits',
            },
        ),
    ]
