# Generated by Django 5.2.7 on 2026-01-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productflash_secondary_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compare_at_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
