# Generated by Django 5.2.7 on 2026-01-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_compare_at_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpromotion',
            name='promo_price',
            field=models.IntegerField(blank=True, help_text='Prix promotionnel', null=True),
        ),
    ]
