# Generated by Django 5.2.8 on 2026-01-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productcarousel_options_productpromotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
