# Generated by Django 5.2.7 on 2026-01-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_productpromotion_promo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashproductitem',
            name='promo_price',
            field=models.IntegerField(blank=True, help_text='Prix promotionnel', null=True),
        ),
    ]
