# Generated by Django 5.2.7 on 2026-01-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_flashproductitem_promo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashproductitem',
            name='compare_at_price',
            field=models.IntegerField(blank=True, help_text='Prix de comparaison (ancien prix)', null=True),
        ),
    ]

