# Generated by Django 5.2.7 on 2026-01-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_flashproductitem_compare_at_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashproductitem',
            name='promo_price',
        ),
    ]
