# Generated by Django 5.2.7 on 2026-02-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_flashproductitem_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productflash',
            name='secondary_products',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez maximum 8 produits secondaires pour ce flash', related_name='flash_secondary', to='api.product'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('commentaire', models.TextField(max_length=1000, verbose_name='Commentaire')),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], help_text='Note de 1 à 5 étoiles', verbose_name='Note')),
                ('is_approved', models.BooleanField(default=False, help_text="Le commentaire doit être approuvé avant d'être visible", verbose_name='Approuvé')),
                ('is_flagged', models.BooleanField(default=False, help_text='Commentaire signalé comme inapproprié', verbose_name='Signalé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_approved'], name='api_comment_product_0f6202_idx'), models.Index(fields=['created_at'], name='api_comment_created_ec94a9_idx')],
            },
        ),
    ]
