# Generated by Django 5.2.7 on 2026-02-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_productflash_secondary_products_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='save_email',
            field=models.BooleanField(default=False, help_text="Le client autorise l'enregistrement de son email", verbose_name="Enregistrer l'email"),
        ),
    ]
