# Generated by Django 5.2.7 on 2026-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_commentaire_save_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrepage',
            name='commentaires_per_page',
            field=models.PositiveIntegerField(default=4, help_text='Nombre de commentaires à afficher initialement sur la page produit'),
        ),
    ]
