# Generated by Django 5.2.8 on 2026-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_parametrepage_commentaires_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrepage',
            name='boutique_products_per_page',
            field=models.PositiveIntegerField(default=24, help_text='Nombre de produits à afficher par page dans la boutique'),
        ),
    ]
