# Generated by Django 5.2.7 on 2026-02-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_paypal_orders'),
        ('api', '0015_pendingpaypalorder_billing_snapshot'),
    ]

    operations = [
    ]
