# Generated by Django 5.2.7 on 2026-02-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20260212_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpaypalorder',
            name='billing_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='{email, first_name, last_name, address, city, country, zip_code, phone}', verbose_name='Snapshot facturation'),
        ),
    ]
