# Generated by Django 5.2.8 on 2026-02-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_pendingpaypalorder_billing_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMTNMoMoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID transaction MTN MoMo')),
                ('cart_snapshot', models.JSONField(default=list, help_text='Liste des items: [{id, name, price, quantity}]', verbose_name='Snapshot du panier')),
                ('billing_snapshot', models.JSONField(blank=True, default=dict, help_text='{email, first_name, last_name, address, city, country, zip_code, phone}', verbose_name='Snapshot facturation')),
                ('total_cfa', models.PositiveIntegerField(default=0, verbose_name='Total CFA')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Montant XAF')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('phone_number', models.CharField(help_text='Numéro au format 237XXXXXXXXX', max_length=20, verbose_name='Numéro de téléphone MTN')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('successful', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], db_index=True, default='pending', max_length=20)),
                ('mtn_response', models.JSONField(blank=True, default=dict, help_text="Réponse complète de l'API MTN MoMo", verbose_name='Réponse MTN MoMo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande MTN Mobile Money en attente',
                'verbose_name_plural': 'Commandes MTN Mobile Money en attente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='mtn_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID transaction MTN MoMo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank', 'Virement bancaire'), ('cheque', 'Chèque'), ('mtn_momo', 'MTN Mobile Money')], default='paypal', max_length=20),
        ),
    ]
