# Generated by Django 5.2.8 on 2026-02-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_pending_orange_money_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrepage',
            name='ma_selection_title',
            field=models.CharField(default='Ma Selection', help_text='Titre de la section Ma Selection', max_length=200),
        ),
    ]
