# Generated by Django 5.2.8 on 2026-02-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_parametrepage_ma_selection_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrepage',
            name='ma_selection_title',
        ),
        migrations.CreateModel(
            name='MaSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ma Selection', help_text='Titre de la section Ma Selection', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text="Activez cette section pour l'afficher sur le site")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Sélectionnez les produits à afficher dans cette section', related_name='ma_selections', to='api.product')),
            ],
            options={
                'verbose_name': 'Ma Selection',
                'verbose_name_plural': 'Ma Selection',
            },
        ),
    ]
